#!/bin/sh
# codie;dots O
# /_  _._     ._ _ /_/ _ 
# /_/_>/_/\/\// / // \\_ 
#      /                 

pgrep -x sxhkd > /dev/null || sxhkd &
 
polybar --reload top &
picom -o 0 &
clight &
nitrogen --restore &

spotify-launcher &


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true

bspc rule -a zen desktop='^2'

bspc rule -a Spotify desktop='^4'
